name: build
on:
  push:
    branches:
      - "*"

jobs:
  notion_job:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: checkout action
        uses: actions/checkout@v3
        with:
          # Custom token to allow commits trigger other workflows.
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16
      - name: change dir
        run: cd ./.github/src
      - name: Install Dependencies
        run: cd ./.github/src && npm install

      - name: Build dist
        run: cd ./.github/src && npm run build

      - name: Commit dist
        uses: EndBug/add-and-commit@v7
        with:
          add: "dist"
          author_name: coresoft
          message: "build"
